[project]
name = "aeon-webfolder-comparison-project"
version = "0.0.0"
description = "Experimental project to compare Aeon webfolders."
readme = "coming"
requires-python = ">=3.12,<3.13"
dependencies = []

[dependency-groups]
local = []
staging = []
prod = []
