[project]
name = "aeon-webfolder-comparison-project"
version = "0.0.0"
description = "Experimental project to compare Aeon webfolders."
readme = "coming"
requires-python = ">=3.12,<3.13"
dependencies = [
    "polars~=1.32.0",
]

[dependency-groups]
local = []
staging = []
prod = []
